version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: grid
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    # image: sravan98/my-express-app:lastest
    build: .
    command: bash -c "npm run migrate:db && npm start"
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_HOST: db
      DB_NAME: grid
      DB_PASSWORD: admin
      DB_PORT: 5432
      SELENIUM_HUB: http://192.168.29.5:4444
    ports:
      - "3000:3000"
volumes:
  db-data:
