# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  db:
      image: postgres:9.6-bullseye
      restart: always
      environment:
        - POSTGRES_USER=seluser
        - POSTGRES_PASSWORD=seluser
        - POSTGRES_DB=selenium_sessions
      ports:
        - "5432:5432"
      volumes:
      - ./NodeDocker/init.sql:/docker-entrypoint-initdb.d/init.sql
  node-docker:
    image: selenium/node-docker:4.7.2-20221217
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.7.2-20221217
    container_name: selenium-hub
    depends_on:
      - db
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"